/* Vorschau im normalen Spielmodus (mit Wartezeiten): startet ein neues Spiel, klickt ein paar
   Dinge an und macht Screenshots. Aufruf: node test/preview.mjs [--shotdir=...] */
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const gRoot = process.env.NODE_PATH || '/usr/lib/node_modules';
const { chromium } = createRequire(path.join(gRoot, 'x.js'))('playwright');
const args = process.argv.slice(2);
const opt = (name, def) => { const a = args.find((x) => x.startsWith('--' + name + '=')); return a ? a.split('=')[1] : def; };
const shotDir = opt('shotdir', path.join(process.env.SCRATCH || '/tmp', 'atl-preview'));
mkdirSync(shotDir, { recursive: true });
const port = 8700 + Math.floor(Math.random() * 200);
const server = spawn('http-server', [root, '-p', String(port), '-s'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 900));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 960, height: 750 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
page.on('console', (m) => { if (m.type() === 'error' && !/AudioContext/.test(m.text())) console.log('[console]', m.text()); });
await page.goto(`http://localhost:${port}/index.html`);
await page.waitForFunction(() => window.ATL && ATL.game && ATL.game.roomDef);
const shot = (n) => page.screenshot({ path: path.join(shotDir, n + '.png') });
const idle = async () => { for (let i = 0; i < 40; i++) { const b = await page.evaluate(() => ATL.game.busy || ATL.game.cutscene); if (!b) return; await page.keyboard.press(' '); await page.waitForTimeout(250); } };
await shot('01-titel');
await page.click('#menu-buttons button:nth-child(1)');
await page.waitForTimeout(3500);
await shot('02-intro-erzaehler');
await page.waitForTimeout(6000);
await shot('03-intro-greaves');
// Intro überspringen
for (let i = 0; i < 12; i++) { await page.keyboard.press(' '); await page.waitForTimeout(150); }
await page.waitForTimeout(1500);
await page.mouse.move(150, 300);
await page.waitForTimeout(200);
await shot('04-hover-regal');
await page.click('#verbs button[data-verb="look"]');
await page.click('#scene', { position: { x: 254, y: 330 } });
await page.waitForTimeout(1800);
await shot('05-schau-globus');
await idle();
await page.click('#scene', { position: { x: 890, y: 300 } });
await page.waitForFunction(() => ATL.game.roomDef.id === 'p_hall' && ATL.game.fade === 0, null, { timeout: 15000 });
await page.waitForTimeout(500);
await shot('06-flur');
await idle();
await page.click('#verbs button[data-verb="talk"]');
await page.click('#scene', { position: { x: 700, y: 450 } });
await page.waitForFunction(() => ATL.game.inDialog, null, { timeout: 15000 });
await page.waitForTimeout(400);
await shot('07-dialog-hank');
await page.click('#dialog .opt:nth-child(1)');
await page.waitForTimeout(2500);
await shot('07b-hank-antwort');
for (let i = 0; i < 6; i++) { await page.keyboard.press(' '); await page.waitForTimeout(200); }
await page.waitForFunction(() => ATL.game.inDialog, null, { timeout: 15000 });
await page.click('#dialog .opt:last-child');
await page.waitForTimeout(2500);
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
await shot('08-menue');
await page.keyboard.press('Escape');
await page.keyboard.press('t');
await page.waitForTimeout(300);
await shot('09-tagebuch');
await browser.close();
server.kill();
console.log('Screenshots in', shotDir);
