/* Komplettlösung Mesopotamien. Schrittarten siehe steps_prolog.mjs. */
export const setup = [
  ['eval', "for (const it of ['taschenmesser','muenzen','flasche','seil','perle','visitenkarte','medaillon','oellampe','schaufel','solontext','sonnensiegel']) g.take(it, {silent:true}); g.set('ny_fertig'); g.set('eg_fertig'); g.set('kessler_geflohen'); g.set('ort','eridu');"],
  ['goto', 'me_camp', 160, 520, 'r'],
];
export const steps = [
  ['room', 'me_camp'], ['flag', 'me_intro'],
  ['act', 'look', 'zikkurat_fern'], ['codex', 'zikkurat'],
  ['act', 'look', 'funkmast'], ['act', 'look', 'fundtisch'], ['act', 'look', 'wassertank'],
  ['act', 'use', 'wassertank', 'flasche'],
  ['act', 'take', 'kanister'], ['hasnot', 'kanister'],
  ['act', 'use', 'jeep'], ['noflag', 'jeep_an_zikkurat'],
  ['queue', 'Funker', 'Silbentafel', 'vorgefallen', 'Bis später'], ['act', 'talk', 'tom'], ['has', 'syllabar'], ['flag', 'syllabar_erhalten'], ['codex', 'keilschrift'],
  ['item', 'use', 'syllabar'], ['item', 'open', 'syllabar'],
  ['queue', 'Whitmore', 'Eingang', 'Bis später'], ['act', 'talk', 'nabil'], ['flag', 'nabil_auftrag'],
  ['act', 'take', 'kanister'], ['hasnot', 'kanister'],
  ['queue', 'Nächstes', 'Eridu', 'Weisen', 'Bis gleich'], ['act', 'talk', 'livia'], ['codex', 'eridu'], ['codex', 'apkallu'],
  ['act', 'walk', 'weg'], ['room', 'me_ziggurat'], ['flag', 'zikkurat_besucht'],
  ['act', 'look', 'stufen'], ['act', 'look', 'block'], ['act', 'push', 'block'], ['noflag', 'block_weg'],
  ['act', 'walk', 'eingang'], ['room', 'me_ziggurat'],
  ['act', 'look', 'zylinder'],
  ['act', 'use', 'zylinder'], ['flag', 'zylinder_gelesen'], ['codex', 'eridu'], ['codex', 'keilschrift'],
  ['act', 'use', 'block', 'seil'], ['flag', 'seil_am_block'], ['has', 'seil'],
  ['act', 'walk', 'lager'], ['room', 'me_camp'],
  ['queue', 'gelesen', 'Abzu', 'Bis später'], ['act', 'talk', 'nabil'], ['has', 'kanister'], ['flag', 'kanister_erhalten'],
  ['act', 'use', 'jeep', 'kanister'], ['flag', 'jeep_betankt'], ['hasnot', 'kanister'],
  ['queue', 'Nächstes', 'Gilgamesch', 'Bis gleich'], ['act', 'talk', 'livia'], ['codex', 'gilgamesch'],
  ['act', 'use', 'jeep'], ['room', 'me_ziggurat'], ['flag', 'jeep_an_zikkurat'],
  ['act', 'use', 'jeep'], ['noflag', 'block_weg'],
  ['act', 'use', 'jeep', 'seil'], ['flag', 'seil_gespannt'], ['hasnot', 'seil'],
  ['eval', "g.set('seil_gespannt', false); g.set('seil_am_block', false); g.take('seil', {silent:true}); g.repaint();"],
  ['act', 'use', 'jeep', 'seil'], ['flag', 'seil_am_jeep'], ['has', 'seil'],
  ['act', 'use', 'jeep'], ['noflag', 'block_weg'],
  ['act', 'use', 'block', 'seil'], ['flag', 'seil_gespannt'], ['hasnot', 'seil'], ['noflag', 'seil_am_jeep'],
  ['act', 'look', 'jeep'],
  ['act', 'use', 'jeep'], ['flag', 'block_weg'], ['has', 'seil'],
  ['act', 'look', 'block_weg'],
  ['act', 'walk', 'eingang'], ['room', 'me_archive'], ['flag', 'archiv_besucht'],
  ['act', 'look', 'statue'], ['act', 'look', 'regal_l'], ['act', 'take', 'regal_l'], ['act', 'look', 'tuer_zu'], ['act', 'open', 'tuer_zu'],
  ['act', 'look', 'fluttafel'],
  ['act', 'use', 'fluttafel', 'syllabar'], ['flag', 'fluttafel_gelesen'], ['has', 'tafeltext'], ['codex', 'gilgamesch'],
  ['item', 'use', 'tafeltext'],
  ['act', 'look', 'relief4'],
  ['act', 'push', 'relief2'], ['noflag', 'weisen_tuer_offen'], ['flag', 'relief_hinweis'],
  ['act', 'push', 'relief7'], ['noflag', 'weisen_tuer_offen'],
  ['act', 'push', 'relief4'], ['flag', 'weisen_tuer_offen'],
  ['act', 'walk', 'tuer'], ['room', 'me_abzu'], ['flag', 'abzu_besucht'],
  ['act', 'look', 'nische'], ['act', 'take', 'nische'], ['hasnot', 'flutsiegel'],
  ['act', 'look', 'wasser'], ['act', 'look', 'tor'], ['act', 'look', 'rad'],
  ['act', 'use', 'rad'], ['noflag', 'wasser_hoch'],
  ['act', 'open', 'tor'], ['noflag', 'tor_zu'],
  ['act', 'close', 'tor'], ['flag', 'tor_zu'],
  ['act', 'use', 'rad'], ['flag', 'wasser_hoch'],
  ['act', 'use', 'rad'],
  ['act', 'use', 'boot'], ['flag', 'boot_im_wasser'],
  ['act', 'look', 'boot_wasser'],
  ['act', 'open', 'tor'], ['noflag', 'wasser_hoch'], ['noflag', 'tor_zu'],
  ['act', 'use', 'boot_wasser'], ['hasnot', 'flutsiegel'],
  ['act', 'close', 'tor'], ['act', 'use', 'rad'], ['flag', 'wasser_hoch'],
  ['act', 'use', 'boot_wasser'], ['has', 'flutsiegel'], ['flag', 'flutsiegel_genommen'],
  ['act', 'look', 'nische'],
  ['act', 'open', 'tor'], ['noflag', 'wasser_hoch'],
  ['act', 'use', 'wasser', 'flasche'],
  ['act', 'walk', 'treppe'], ['room', 'me_archive'],
  ['act', 'walk', 'ausgang'], ['room', 'me_ziggurat'],
  ['act', 'walk', 'lager'], ['room', 'me_camp'], ['flag', 'me_fertig'], ['flag', 'tom_meridian'],
  ['queue', 'Nächstes', 'Bis gleich'], ['act', 'talk', 'livia'],
  ['act', 'give', 'livia', 'flutsiegel'], ['has', 'flutsiegel'],
  ['act', 'walk', 'piste'], ['room', 'map'],
];
