export const setup = [
  ['eval', "g.take('perle',{silent:true}); g.take('visitenkarte',{silent:true}); g.take('seil',{silent:true}); g.take('flasche',{silent:true}); g.set('kessler_geflohen'); g.set('prolog_fertig'); g.set('ort','newyork');"],
  ['goto', 'ny_street', 200, 520, 'r'],
];
export const steps = [
  ['room', 'ny_street'],
  ['act', 'look', 'plakat'], ['act', 'look', 'zeitungen'],
  ['queue', 'Männer in schwarzen', 'Schönen Abend'], ['act', 'talk', 'tuersteher'], ['flag', 'meridian_drin'],
  ['act', 'walk', 'eingang'], ['room', 'ny_street'],
  ['queue', 'Berliner Jacht', 'Mach'], ['act', 'talk', 'zeitungsjunge'], ['flag', 'vesper_in_ny'],
  ['queue', 'Bühneneingang', 'Danke'], ['act', 'talk', 'verkaeufer'],
  ['act', 'give', 'verkaeufer', 'muenzen'], ['has', 'hotdog', 'muenzen'],
  ['act', 'walk', 'gasse'], ['room', 'ny_alley'],
  ['act', 'open', 'buehnentuer'], ['act', 'talk', 'katze'], ['act', 'open', 'muelltonnen'], ['flag', 'flugblatt'],
  ['act', 'give', 'katze', 'hotdog'], ['flag', 'leiter_unten'], ['hasnot', 'hotdog'],
  ['act', 'walk', 'hinauf'], ['room', 'ny_dressing'],
  ['act', 'use', 'notizbuch'], ['codex', 'solon'],
  ['act', 'open', 'koffer'],
  ['queue', 'gut aus', 'Kessler', 'Welches Medaillon', 'Ich habe die Perle', 'College verlassen', 'Gehen wir'], ['act', 'walk', 'tuer'],
  ['room', 'ny_stage'], ['flag', 'livia_versteck'],
  ['act', 'look', 'leinwand'], ['codex', 'ringe'],
  ['queue', 'Metall', 'Ich hole'], ['act', 'talk', 'livia'], ['codex', 'orichalkum'],
  ['act', 'open', 'modell'],
  ['act', 'use', 'modell', 'taschenmesser'], ['flag', 'modell_offen'],
  ['act', 'take', 'medaillon'], ['has', 'medaillon'], ['flag', 'medaillon_genommen'],
  ['act', 'open', 'falltuer'], ['room', 'ny_street'], ['flag', 'flucht'], ['flag', 'ny_fertig'],
  ['queue', 'Sais', 'brennenden Berg', 'Hafen'], ['act', 'talk', 'livia'],
  ['act', 'walk', 'taxi'], ['room', 'map'],
];
