/* Komplettlösung Kreta. Vorbereitung: alles, was Falk aus Prolog, New York und Ägypten mitbringt. */
export const setup = [
  ['eval', "['taschenmesser','muenzen','flasche','seil','perle','visitenkarte','medaillon','oellampe','schaufel','solontext','sonnensiegel'].forEach((i) => g.take(i, { silent: true })); g.drop('uhr'); g.set('ny_fertig'); g.set('eg_fertig'); g.set('kessler_geflohen'); g.set('ort', 'kreta');"],
  ['goto', 'cr_village', 160, 520, 'r'],
];
export const steps = [
  ['room', 'cr_village'], ['flag', 'kreta_intro'],
  ['act', 'look', 'ziege'], ['act', 'look', 'kapelle'], ['act', 'look', 'netze'],
  ['act', 'give', 'ziege', 'seil'], ['has', 'seil'],
  ['act', 'pull', 'ziege'], ['act', 'look', 'livia'], ['act', 'look', 'yannis'],
  ['queue', 'Labyrinth', 'Faden', 'Stier', 'Minoer', 'Was jetzt', 'Bis später'], ['act', 'talk', 'livia'],
  ['codex', 'minotaurus'], ['codex', 'ariadne'], ['codex', 'stier'], ['codex', 'minoer'],
  ['queue', 'Netze', 'Knossos', 'Ziege', 'Fremder', 'Bis später'], ['act', 'talk', 'yannis'], ['flag', 'kessler_gesehen'],
  ['act', 'walk', 'taverne'], ['room', 'cr_taverna'],
  ['act', 'look', 'maria'], ['act', 'look', 'bramwell'], ['act', 'look', 'eleni'], ['act', 'give', 'bramwell', 'muenzen'],
  ['queue', 'Raki', 'Oliven', 'Engländer', 'Strickzeug', 'Fremdes', 'Palast', 'danke'], ['act', 'talk', 'maria'], ['has', 'raki', 'oliven'],
  ['queue', 'gegraben', 'Krypta', 'Fremder', 'Labyrinth', 'Hut'], ['act', 'talk', 'bramwell'], ['flag', 'bramwell_hut_wunsch'], ['hasnot', 'plan'],
  ['queue', 'stricken', 'Knäuel', 'Herakles', 'Theseus', 'Pasiphae', 'Ariadne', 'Tasche', 'festgebunden'], ['act', 'talk', 'eleni'], ['has', 'wolle'], ['flag', 'eleni_wolle'],
  ['act', 'look', 'deko'], ['codex', 'labrys'],
  ['act', 'open', 'faesser'],
  ['act', 'walk', 'tuer'], ['room', 'cr_village'],
  ['act', 'give', 'ziege', 'oliven'], ['has', 'hut'], ['hasnot', 'oliven'], ['flag', 'hut_genommen'],
  ['act', 'give', 'yannis', 'raki'], ['hasnot', 'raki'], ['flag', 'yannis_legende'],
  ['act', 'walk', 'taverne'], ['room', 'cr_taverna'],
  ['act', 'give', 'bramwell', 'hut'], ['has', 'plan'], ['hasnot', 'hut'], ['flag', 'bramwell_plan'],
  ['item', 'use', 'plan'], ['flag', 'plan_gelesen'],
  ['queue', 'Raki', 'danke'], ['act', 'talk', 'maria'], ['has', 'raki'],
  ['act', 'walk', 'tuer'], ['room', 'cr_village'],
  ['queue', 'Was jetzt', 'Bis später'], ['act', 'talk', 'livia'],
  ['act', 'walk', 'weg'], ['room', 'cr_knossos'], ['flag', 'knossos_intro'],
  ['act', 'look', 'fresko'], ['codex', 'stier'], ['codex', 'minotaurus'], ['codex', 'minoer'],
  ['act', 'look', 'thron'], ['codex', 'knossos'],
  ['act', 'look', 'kulthoerner'], ['act', 'look', 'saeulen'],
  ['act', 'open', 'pithos2'],
  ['act', 'push', 'pithos'],
  ['act', 'open', 'pithos'], ['has', 'doppelaxt'], ['flag', 'doppelaxt_genommen'],
  ['act', 'walk', 'abgang'], ['room', 'cr_crypt'], ['flag', 'krypta_intro'],
  ['act', 'look', 'pfeiler'],
  ['act', 'push', 'axt_l'], ['noflag', 'krypta_offen'],
  ['act', 'push', 'axt_r'], ['noflag', 'krypta_offen'],
  ['act', 'push', 'platte'], ['act', 'use', 'platte', 'schaufel'],
  ['act', 'push', 'axt_m'], ['flag', 'krypta_offen'],
  ['act', 'look', 'ring'], ['act', 'look', 'gang'],
  ['act', 'use', 'ring', 'seil'], ['noflag', 'faden'],
  ['act', 'walk', 'gang'], ['room', 'cr_crypt'], ['flag', 'faden_gewarnt'],
  ['act', 'use', 'ring', 'wolle'], ['flag', 'faden'], ['has', 'wolle'],
  ['act', 'walk', 'gang'], ['room', 'cr_bullchamber'], ['flag', 'halle_intro'],
  ['act', 'look', 'stierkopf'], ['act', 'look', 'maul'], ['act', 'look', 'grube'], ['act', 'look', 'altar'],
  ['act', 'open', 'maul'], ['noflag', 'maul_offen'],
  ['act', 'use', 'maul', 'doppelaxt'], ['has', 'doppelaxt'],
  ['act', 'use', 'schale', 'flasche'],
  ['act', 'walk', 'ausgang'], ['room', 'cr_crypt'],
  ['act', 'walk', 'gang'], ['room', 'cr_bullchamber'],
  ['act', 'use', 'schale', 'raki'], ['flag', 'maul_offen'], ['hasnot', 'raki', 'doppelaxt'],
  ['act', 'look', 'siegel'],
  ['queue', 'knapp an Leuten', 'gefunden', 'Vesper mit dem Siegel', 'umkehren', 'Kommen Sie'], ['act', 'take', 'siegel'],
  ['has', 'stiersiegel'], ['flag', 'siegel_genommen'], ['flag', 'kessler_da'], ['flag', 'kessler_kreta'], ['flag', 'kessler_liegt'],
  ['act', 'look', 'kessler_liegt'],
  ['act', 'walk', 'ausgang'], ['room', 'cr_crypt'], ['flag', 'kessler_weg'],
  ['act', 'walk', 'treppe'], ['room', 'cr_knossos'],
  ['act', 'walk', 'dorf'], ['room', 'cr_village'],
  ['queue', 'Siegel', 'Bis später'], ['act', 'talk', 'livia'], ['flag', 'siegel_gedeutet'],
  ['has', 'stiersiegel', 'sonnensiegel', 'wolle', 'plan', 'oellampe'],
  ['act', 'walk', 'karte'], ['room', 'map'],
];
