/* Komplettlösung Thera. Fixture: alles, was Falk laut DESIGN.md mitbringt. */
export const setup = [
  ['eval', "for (const it of ['taschenmesser', 'muenzen', 'flasche', 'seil', 'perle', 'visitenkarte', 'medaillon', 'oellampe', 'schaufel', 'solontext', 'sonnensiegel', 'stiersiegel', 'flutsiegel']) g.take(it, { silent: true }); g.set('ny_fertig'); g.set('eg_fertig'); g.set('kessler_geflohen'); g.set('ort', 'thera');"],
  ['goto', 'th_harbor', 200, 520, 'r'],
];
export const steps = [
  ['room', 'th_harbor'], ['flag', 'th_angekommen'],
  ['act', 'look', 'jacht'], ['act', 'look', 'vulkan'], ['codex', 'thera'],
  ['act', 'look', 'kohlenbecken'], ['act', 'look', 'beiboot'], ['act', 'look', 'esel'],
  ['act', 'use', 'beiboot'], ['hasnot', 'zuendkerze'],
  ['act', 'walk', 'boot_stavros'],
  ['queue', 'Was weißt du über das Tor', 'Orichalkum', 'Wie kommen wir', 'Was ist mit Vesper', 'Ich sehe mich um'], ['act', 'talk', 'livia'], ['codex', 'ringe'], ['codex', 'orichalkum'],
  ['queue', 'Können Sie mich', 'Wo bekommt man', 'Kennen Sie die Leute', 'Bis später'], ['act', 'talk', 'stavros'], ['flag', 'stavros_gefragt'],
  ['queue', 'Ich wollte nur', 'Gehört das Boot', 'Schon gut'], ['act', 'talk', 'wache'],
  ['queue', 'Was kosten die Kracher', 'Was ist das für ein Fest', 'Kennen Sie die Männer', 'Danke'], ['act', 'talk', 'kiosk'], ['has', 'feuerwerk'],
  ['act', 'give', 'kiosk', 'muenzen'], ['has', 'zigaretten'], ['has', 'muenzen'],
  ['act', 'give', 'wache', 'zigaretten'], ['has', 'zigaretten'],
  ['act', 'give', 'stavros', 'zigaretten'], ['flag', 'stavros_erzaehlt'], ['hasnot', 'zigaretten'],
  ['act', 'use', 'kohlenbecken', 'feuerwerk'], ['flag', 'wache_abgelenkt'], ['hasnot', 'feuerwerk'],
  ['act', 'take', 'beiboot'], ['has', 'zuendkerze'], ['flag', 'zuendkerze_genommen'],
  ['act', 'give', 'stavros', 'zuendkerze'], ['flag', 'stavros_faehrt'], ['hasnot', 'zuendkerze'],
  ['queue', 'Wann fahren wir', 'Bis später'], ['act', 'talk', 'stavros'],
  ['act', 'walk', 'boot'], ['room', 'th_cliff'], ['flag', 'th_bucht_besucht'],
  ['act', 'look', 'klippen'], ['act', 'look', 'ziegen'], ['act', 'look', 'wache'],
  ['queue', 'Wo ist die Grabung', 'Ich gehe dann'], ['act', 'talk', 'stavros'],
  ['act', 'walk', 'pfad'], ['room', 'th_cliff'], ['noflag', 'pfad_frei'],
  ['act', 'take', 'stein'], ['has', 'stein'],
  ['act', 'take', 'bimsschicht'], ['has', 'bimsstein'],
  ['act', 'use', 'ziegen', 'bimsstein'], ['has', 'bimsstein'],
  ['act', 'use', 'ziegen', 'stein'], ['flag', 'pfad_frei'], ['hasnot', 'stein'],
  ['act', 'walk', 'pfad'], ['room', 'th_akrotiri'], ['flag', 'th_akrotiri_besucht'],
  ['act', 'look', 'fresko_schiffe'], ['codex', 'fresken'], ['act', 'look', 'fresko_fruehling'], ['act', 'look', 'tor'],
  ['act', 'use', 'tor'], ['noflag', 'tor_offen'],
  ['act', 'open', 'zelt_vesper'], ['flag', 'zelt_offen'],
  ['act', 'use', 'notizen'], ['flag', 'notizen_gelesen'],
  ['act', 'take', 'brecheisen'], ['has', 'brecheisen'], ['flag', 'brecheisen_genommen'],
  ['act', 'use', 'tor', 'brecheisen'],
  ['act', 'use', 'tor', 'sonnensiegel'], ['hasnot', 'sonnensiegel'], ['flag', 'tor_sonne'],
  ['act', 'use', 'tor'], ['noflag', 'tor_offen'],
  ['act', 'use', 'tor', 'stiersiegel'], ['hasnot', 'stiersiegel'], ['flag', 'tor_stier'],
  ['act', 'use', 'tor', 'flutsiegel'], ['hasnot', 'flutsiegel'], ['flag', 'tor_flut'],
  ['eval', "return g.flag('siegel_im_tor') === 3;"],
  ['queue', 'Sie bekommen es nicht', 'Lassen Sie Livia gehen', 'Hier'],
  ['act', 'use', 'tor'], ['flag', 'tor_offen'], ['flag', 'tor_hinweis'], ['flag', 'livia_gefangen'], ['flag', 'th_fertig'], ['hasnot', 'medaillon'], ['has', 'perle'],
  ['room', 'th_descent'], ['flag', 'th_descent_besucht'],
  ['act', 'look', 'saeulen'], ['act', 'look', 'inschrift'], ['codex', 'ringe'], ['act', 'look', 'buehne'],
  ['act', 'walk', 'zurueck'], ['room', 'th_descent'],
  ['act', 'pull', 'hebel'], ['noflag', 'th_abgestiegen'],
  ['act', 'use', 'buehne', 'perle'], ['has', 'perle'],
  ['act', 'use', 'sockel', 'perle'], ['flag', 'perle_im_sockel'], ['hasnot', 'perle'],
  ['flag', 'livia_gefangen'], ['flag', 'th_fertig'], ['has', 'brecheisen', 'bimsstein', 'seil'],
  // Letzter Schritt: at_outer wird von einem anderen Kapitel gebaut; fehlt der Raum, wird nur der Flag geprüft.
  ['eval', "return (async () => { const h = g.hs('hebel'); try { await h.pull(g); } catch (e) { console.log('Hinweis: ' + e.message); } g.busy = false; g.phase = null; g.cutscene = false; g.dark = 0; if (g.ui) g.ui.setCutscene(false); return !!g.flag('th_abgestiegen'); })();"],
];
